services:
  - type: worker
    name: retale-system-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DISCORD_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false 